### ISSUE TITLE
Feature Request:  Add "in" topic

### ISSUE THREAD

**Issue by dp106** [OctoPrint/OctoPrint-MQTT#26] opened 2018-01-08 09:08 UTC
As far as I can see the plugin only sends out messages but cannot receive any?  It would be great to be able to send some commands in to OctoPrint in this way, to instruct it to connect to the printer for example.

I am currently using the api successfully to do this, just thought if it were possible to use this it would feel cleaner being able to design flows in nodered

**Comment by derpicknicker1** [comment] 2018-01-12 08:39
The plugin has helpers to subscribe and publish to topics. This can be used by other Plugins. So you are welcom to write your own plugin to handle commands via mqtt.

**Comment by foosel** [comment] 2018-01-31 09:59
Duplicate of #20

**Closed by foosel** 2018-01-31 09:59 UTC
