### ISSUE TITLE
Topic is sometimes wrongly formatted

### ISSUE THREAD

**Issue by Kunsi** [OctoPrint/OctoPrint-MQTT#12] opened 2017-05-15 12:17 UTC
Note: I'm currently working on a rework, this is more a Note book and ToDo list than a bug report

octoprint/opalblau/event/('FileAdded',) {"path": "aaa-test/9021e438-6016-4577-b161-50e5484c6c7b.gcode", "_event": ["FileAdded"], "storage": "local", "name": "9021e438-6016-4577-b161-50e5484c6c7b.gcode", "type": ["machinecode", "gcode"]}

**Comment by foosel** [comment] 2017-07-12 14:31
Turns out that this was actually caused by a bug in OctoPrint which [I've just fixed](https://github.com/foosel/OctoPrint/commit/a33f44ea2508aaa5591eb86ff24ffe57d3aa2e7d). Fix will be released with 1.3.5.

**Closed by foosel** 2017-07-12 14:31 UTC
