### ISSUE TITLE
Feature request: Publish remaining time

### ISSUE THREAD

**Issue by mkh595** [OctoPrint/OctoPrint-MQTT#50] opened 2018-10-18 08:05 UTC
In the terminal I see that there is regulary issued command M73.
```
Send: N17240 M73 P9 R353*25
Recv: NORMAL MODE: Percent done: 9; print time remaining in mins: 353
Recv: SILENT MODE: Percent done: 9; print time remaining in mins: 358
Recv: ok

```
Can be 'Percent done' and 'remaining time' published?

**Comment by jneilliii** [comment] 2018-10-18 12:40
Duplicate of #16.

**Closed by jneilliii** 2018-10-18 12:40 UTC
